# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Description"
  url = "#description"
  weight = 1

[[main]]
  name = "Resources"
  url = "#skills"
  weight = 2

[[main]]
  name = "Docs"
  url = "/docs"
  weight = 3

[[main]]
  name = "Syllabus"
  url = "https://slu-soc5650.github.io/syllabus"
  weight = 4

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 9

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

# Documentation menu

[[docs]]
  name = "Overview"
  url = "/docs/"
  weight = 5 

[[docs]]
  name = "Getting Started"
  weight = 10
  
[[docs]]
  name = "Fundamentals"
  weight = 20

[[docs]]
  name = "Lectures"
  weight = 30
  
[[docs]]
  name = "Final Project"
  url = "/docs/project"
  weight = 40  

[[docs]]
  name = "Topics"
  weight = 50  
  