language: r
dist: trusty
sudo: required

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

before_script:
  - "Rscript -e 'blogdown::install_hugo()'"

script:
  - "Rscript -e 'blogdown::build_site()'"

addons:
  postgresql: "9.6"

r_packages:
  - devtools

before_install:
  - chmod +x ./.travis/install.sh
  - ./.travis/install.sh

after_success:
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  repo: slu-soc5650/slu-soc5650.github.io
  target_branch: master
  