baseurl = "https://slu-soc5650.github.io/"
languageCode = "en-us"
title = "SLU SOC 4650 & SOC 5650"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Christopher Prener, Ph.D."
	description = "SOC 4650 & SOC 5650: Introduction to Geographic Information Science"
	copyright = "Licensed under a CC BY-SA 4.0 License"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/slu-soc5650/Core-Documents"

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "slu-soc5650"
	email   = "chris.prener@slu.edu"
	web     = "https://chris-prener.github.io"


[[menu.main]]
	name   = "About"
	url    = "/"
	weight = 1
	
[[menu.main]]
	name   = "Course Resources"
	url    = "course-resources/"
	weight = 2

[[menu.main]]
	name   = "Course Onboarding"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Course Software"
	url    = "course-software/"
	weight = 11

[[menu.main]]
	name   = "Course Preview"
	url    = "course-preview/"
	weight = 15

[[menu.main]]
	name   = "Lecture 01 - Course Introduction"
	url    = "lecture-01/"
	weight = 20

[[menu.main]]
	name   = "Lecture 02 - Working with Data (1)"
	url    = "lecture-02/"
	weight = 21

[[menu.main]]
	name   = "Lecture 03 - Spatial Data (1)"
	url    = "lecture-03/"
	weight = 22

[[menu.main]]
	name   = "Lecture 04 - Spatial Data (2)"
	url    = "lecture-04/"
	weight = 23

[[menu.main]]
	name   = "Lecture 05 - Cartographic Design"
	url    = "lecture-05/"
	weight = 24

[[menu.main]]
	name   = "Lecture 06 - GIS Outputs"
	url    = "lecture-06/"
	weight = 25

[[menu.main]]
	name   = "Lecture 07 - Geodatabases"
	url    = "lecture-07/"
	weight = 26

[[menu.main]]
	name   = "Lecture 08 - Demographic Data"
	url    = "lecture-08/"
	weight = 27

[[menu.main]]
	name   = "Lecture 09 - Spatial Joins"
	url    = "lecture-09/"
	weight = 28

[[menu.main]]
	name   = "Lecture 10 - Projections"
	url    = "lecture-10/"
	weight = 29

[[menu.main]]
	name   = "Lecture 11 - Working with Data (2)"
	url    = "lecture-11/"
	weight = 30

[[menu.main]]
	name   = "Lecture 12 - Geoprocessing (1)"
	url    = "lecture-12/"
	weight = 31

[[menu.main]]
	name   = "Lecture 13 - Geoprocessing (2)"
	url    = "lecture-13/"
	weight = 32

[[menu.main]]
	name   = "Final Project"
	url    = "final-project/"
	weight = 40

[[menu.main]]
	name   = "Topic Index"
	url    = "topic-index/"
	weight = 41

[[menu.main]]
	name   = "Package Index"
	url    = "package-index/"
	weight = 42

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 45
	
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
