baseurl = "https://slu-soc5650.github.io/"
languageCode = "en-us"
title = "SLU SOC 4650 & SOC 5650"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Christopher Prener, Ph.D."
	description = "SOC 4650 & SOC 5650: Introduction to Geographic Information Science"
	copyright = "Licensed under a CC BY-NC 4.0 License"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/slu-soc5650/Core-Documents"

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "slu-soc5650"
	email   = "chris.prener@slu.edu"
	web     = "https://chris-prener.github.io"


[[menu.main]]
	name   = "About"
	url    = "/"
	weight = 1
	
[[menu.main]]
	name   = "Course Resources"
	url    = "course-resources/"
	weight = 2

[[menu.main]]
	name   = "Course Onboarding"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Course Preview"
	url    = "course-preview/"
	weight = 15

[[menu.main]]
	name   = "Lecture 01 - Course Introduction"
	url    = "lecture-01/"
	weight = 20

[[menu.main]]
	name   = "Final Project"
	url    = "final-project/"
	weight = 40

[[menu.main]]
	name   = "Topic Index"
	url    = "topic-index/"
	weight = 41

[[menu.main]]
	name   = "Package Index"
	url    = "package-index/"
	weight = 42

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 45
	
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
