---
date: 2019-02-12
title: "Example of Live Leaflet Map"
weight: 21
output:
  blogdown::html_page
---

## St. Louis Population Density (2017)
During class last night, we worked up to building a very similar map to the one served up below. The only difference between the maps we were working on and what is displayed here is that I'm using the Jenk's natural breaks technique for determining the mapping classes.
<p> </p>
```{r echo=FALSE, message=FALSE, warning=FALSE}
# dependencies
library(dplyr)
library(here)
library(leaflet)
library(sf)

# load data
load(file = here("static", "data", "popChange.rda"))

# re-project
popChange <- st_transform(popChange, crs = 4326)

# calculate population density
popChange <- mutate(popChange, pop17_den = pop17/(AREA/1000000))

# create breaks
cp_bins <- function(.data, var, n = 5, style = "jenks", round = 0, dig = 10){
  
  # calculate breaks
  breaks <- classInt::classIntervals(.data[[var]], n = n, style = style)
  categories <- cut(.data[[var]], breaks = c(breaks$brks), include.lowest = TRUE, dig.lab = dig)
  
  # parse categories
  categories <- unique(categories)
  categories <- gsub("[][()]", "", categories)
  categories <- gsub(",", " ", categories)
  categories <- stringr::word(categories, 2)
  categories <- round(as.numeric(categories), digits = round)
  bins <- c(0, categories)
  
  # return output
  return(bins)
  
}

# calculate breaks
bins <- cp_bins(popChange, var = "pop17_den")

# create color palette
pal <- colorBin("YlGnBu", domain = popChange$pop17_den, bins = bins)

# create map
popChange %>%
  leaflet(width = '100%', height = '450pt') %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    color = "#444444", 
    weight = 1, 
    opacity = 1.0, 
    smoothFactor = 0.5,
    fillOpacity = 0.5,
    fillColor = ~pal(pop17_den),
    highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = TRUE),
    popup = paste("<b>Name:</b> ", popChange$NHD_NAME, "<br>",
                  "<b>2017 Population:</b> ", round(popChange$pop17, digits = 0), "<br>",
                  "<b>2017 Population Density (per Km^2):</b> ", round((popChange$pop17_den), digits = 0),"<br>",
                  "<b>Area (Km^2):</b> ", round(popChange$AREA/1000000, digits = 2))) %>%
    addLegend(pal = pal, values = ~pop17_den, opacity = .5, 
              title = "Population Density (2017)")
```
<p> </p>

## How I Made This Map
If you want to re-create this map, you'll need to download the [neighborhood change shapefile](https://github.com/slu-soc5650/lecture-05/tree/master/data/example-data/STL_DEMOS_Nhoods). The code I used is below. The `cp_bins()` function is a custom one that I wrote to calculate the Jenks breaks. This is used to calculate the palette used on the map. Another departure from last night is that I stored the population density in a new variable, `pop17_den`, that I refer to throughout the `leaflet()` call. This makes the code a bit easier to read and reduces the chances of typos. We'll talk about creating new variables in a couple of weeks!

<script src="https://gist.github.com/chris-prener/2706df78f7835bcd2bb9298f5a9aecfd.js"></script>

